[versions]
agp = "8.7.2"
kotlin = "1.9.24"
playServicesWearable = "19.0.0"
tiles = "1.4.1"

[libraries]
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
tiles = { module = "androidx.wear.tiles:tiles", version.ref = "tiles" }
tiles-material = { module = "androidx.wear.tiles:tiles-material", version.ref = "tiles" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

